const jwt = require('jsonwebtoken');

function getFirstEnv(...names) {
  for (const name of names) {
    const v = process.env[name];
    if (v != null && v !== '') return v;
  }
  return undefined;
}

function cleanToken(input) {
  if (!input || typeof input !== 'string') return '';
  return input.trim().replace(/^(Bearer|JWT|Token)\s+/i, '');
}

function verifyExternalToken(token, options = {}) {
  const raw = cleanToken(token);
  if (!raw) {
    const err = new Error('Token is required');
    err.code = 'TOKEN_REQUIRED';
    throw err;
  }
  const rawSecret = getFirstEnv('JWT_SECRET');
  if (!rawSecret) {
    const err = new Error('JWT secret not configured');
    err.code = 'JWT_SECRET_MISSING';
    throw err;
  }
  const issuer = getFirstEnv('JWT_ISSUER', 'TOKEN_ISSUER', 'AUTH_ISSUER');
  const audience = getFirstEnv('JWT_AUDIENCE', 'TOKEN_AUDIENCE', 'AUTH_AUDIENCE') || 'booking-service';
  const verifyOpts = { algorithms: ['HS256'], ...options };
  if (issuer) verifyOpts.issuer = issuer;
  if (audience) verifyOpts.audience = audience;

  // Support base64-encoded secrets (optional)
  const isBase64Flag = process.env.JWT_SECRET_IS_BASE64 === '1' || process.env.ALLOW_BASE64_JWT_SECRET === '1';
  let verified;
  let firstError;
  try {
    verified = jwt.verify(raw, rawSecret, verifyOpts);
  } catch (e1) {
    firstError = e1;
    if (isBase64Flag) {
      try {
        const base64Secret = Buffer.from(String(rawSecret), 'base64');
        verified = jwt.verify(raw, base64Secret, verifyOpts);
      } catch (e2) {
        throw e2;
      }
    } else {
      throw e1;
    }
  }

  // Require minimal claims only
  if (!verified || verified.id == null || verified.type == null) {
    const err = new Error('Token missing required claims: id/type');
    err.code = 'TOKEN_INVALID_CLAIMS';
    throw err;
  }
  return verified;
}

// decodeExternalToken and resolveEntityFromToken removed; not needed in Booking service

function scheduleTokenExpiryDisconnect(socket, decoded) {
  // Tokens are generated by external auth-service. Configure that service to set exp to 1 day (86400s).
  // We still honor exp here, which now should be at least 1 day from issuance.
  if (!decoded || !decoded.exp) return;
  const expiryMs = decoded.exp * 1000;
  const delay = expiryMs - Date.now();
  if (!Number.isFinite(delay) || delay <= 0) {
    try { socket.emit('auth_error', { code: 'TOKEN_EXPIRED', message: 'Authentication token expired.' }); } catch (_) {}
    try { socket.disconnect(true); } catch (_) {}
    return;
  }
  const timer = setTimeout(() => {
    try { socket.emit('auth_error', { code: 'TOKEN_EXPIRED', message: 'Authentication token expired.' }); } catch (_) {}
    try { socket.disconnect(true); } catch (_) {}
  }, delay);
  if (timer.unref) timer.unref();
  socket.once('disconnect', () => clearTimeout(timer));
}

async function socketAuth(socket, next) {
  const authHeader = socket.handshake.auth?.token
    || socket.handshake.query?.token
    || socket.handshake.headers?.authorization;
  try {
    const claims = verifyExternalToken(authHeader);
    socket.user = {
      id: claims.id != null ? String(claims.id) : undefined,
      type: String(claims.type || '').toLowerCase(),
      name: claims.name,
      phone: claims.phone,
      email: claims.email,
      vehicleType: claims.vehicleType,
      carName: claims.carName,
      carModel: claims.carModel,
      carPlate: claims.carPlate,
      carColor: claims.carColor,
    };
    socket.authToken = authHeader && String(authHeader).startsWith('Bearer ') ? String(authHeader) : `Bearer ${String(authHeader || '')}`;
    scheduleTokenExpiryDisconnect(socket, claims);
    return next();
  } catch (err) {
    return next(err);
  }
}

module.exports = { socketAuth, verifyExternalToken };

